/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleOdev;

import java.util.ArrayList;

import static spark.Spark.get;
import static spark.Spark.port;
import static spark.Spark.post;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import javax.lang.model.util.ElementScanner6;

import spark.ModelAndView;
import spark.template.mustache.MustacheTemplateEngine;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static ArrayList<Integer>  compute (ArrayList<Integer> array, int e,String proces) {
      ArrayList<Integer> arr = new ArrayList<Integer>(array.size());
      int element;
      for (int i = 0; i < array.size() ; i++){
        if(proces.equals("/")){
          element=array.get(i)/e;
        }else if(proces.equals("*")){
          element=array.get(i)*e;
        }else if(proces.equals("+")){
          element=array.get(i)+e;
        }else{
          element=array.get(i)-e;
        }
        arr.add(i, element);
      }
;      return arr;
    }



    public static void main(String[] args) {
        port(getHerokuAssignedPort());

        get("/", (req, res) -> "Hello, World");
    
        post("/compute", (req, res) -> {
          //System.out.println(req.queryParams("input1"));
          //System.out.println(req.queryParams("input2"));

          String input1 = req.queryParams("input1");
          java.util.Scanner sc1 = new java.util.Scanner(input1);
          sc1.useDelimiter("[;\r\n]+");
          java.util.ArrayList<Integer> inputList = new java.util.ArrayList<>();
          
          while (sc1.hasNext())
          {
            int value = Integer.parseInt(sc1.next().replaceAll("\\s",""));
            inputList.add(value);
          }
          sc1.close();
          System.out.println(inputList);


          String input2 = req.queryParams("input2").replaceAll("\\s","");
          int input2AsInt = Integer.parseInt(input2);

          String input3=req.queryParams("input3");

          ArrayList<Integer> result = App.compute(inputList, input2AsInt,input3);
          String re="";
          for(int i = 0; i  < result.size();i++){
            re+=result.get(i)+" ";
          }
          System.out.println(re);
          Map<String, String > map = new HashMap<String,String>();
          map.put("result",re);
          return new ModelAndView(map, "compute.mustache");
        }, new MustacheTemplateEngine());


        get("/compute",
            (rq, rs) -> {
              Map<String, String> map = new HashMap<String, String>();
              map.put("result", "not computed yet!");
              return new ModelAndView(map, "compute.mustache");
            },
            new MustacheTemplateEngine());
    }

    static int getHerokuAssignedPort() {
        ProcessBuilder processBuilder = new ProcessBuilder();
        if (processBuilder.environment().get("PORT") != null) {
            return Integer.parseInt(processBuilder.environment().get("PORT"));
        }
        return 4567; //return default port if heroku-port isn't set (i.e. on localhost)
    }

}
